### ISSUE TITLE
[1.0.78.009] Removing "Stone" as a result from All asteroids causes div/0

### ISSUE THREAD

**Issue by MiChAeLoKGB** [MiChAeLoKGB/SpaceEngineers#2]
Working on a stoneless mod and If I change all Stone in VoxelMaterials to something else I get a divide by zero error. 
As long as any 1 material is flagged <MinedOre>Stone</MinedOre> there is no crash.

```
2015-04-20 18:23:12.726 - Thread: 1 -> MyGuiScreenGamePlay.LoadData - END
2015-04-20 18:23:12.727 - Thread: 1 -> MyGuiScreenGamePlay.LoadContent - START
2015-04-20 18:23:12.727 - Thread: 1 -> MyGuiScreenGamePlay.LoadContent - END
2015-04-20 18:23:12.814 - Thread: 1 -> Updating continues.
2015-04-20 18:23:12.859 - Thread: 1 -> Exception occured: System.DivideByZeroException: Attempted to divide by zero.
at =5ZpRFa2vGklloJXCjenzwtNPXp=.Generator(Int32 , Int32 , Single , =HBOutSsXv1sxgB6MATA0wnUzQz=& )
at =n5VCpUPXSPW6SlU1CgRiJFP11f=.GenerateObjects(List`1 )
at =n5VCpUPXSPW6SlU1CgRiJFP11f=.GenerateObjects(BoundingSphereD )
at =n5VCpUPXSPW6SlU1CgRiJFP11f=.UpdateBeforeSimulation()
at =GND6z8idGdIAcWcb2YBaSnRMp7=.UpdateComponents()
at =GND6z8idGdIAcWcb2YBaSnRMp7=.Update(MyTimeSpan )
at =JbLZcQ0hj347engCZ44EtlRZjA=.Update()
at =f3Z6Ndh0u8AiCd1RYvZsU5Dv7T=.UpdateInternal()
at =cuDXH07IPdNc3nh2dfXC4sNbx5=.=v0NoMtrPy2fhNeFawOHPKRCSMn=.<Run>b__1()
at =mEhFnRRYUxEvoh0t4KZxxONkWU=.Run(=ikvYbcjVoXAAj7Kp0pbE1O7j9B= )
at =cuDXH07IPdNc3nh2dfXC4sNbx5=.Run(=ikvYbcjVoXAAj7Kp0pbE1O7j9B= )
at =JbLZcQ0hj347engCZ44EtlRZjA=.Run(Boolean , Action )
at Sandbox.AppCode.App.MyProgram.RunInternal(String[] args)
at Sandbox.AppCode.App.MyProgram.Main(String[] args)
2015-04-20 18:23:12.860 - Thread: 1 -> Hiding window
2015-04-20 18:23:13.363 - Thread: 1 -> Hiding window done
2015-04-20 18:23:13.363 - Thread: 1 -> Showing message
```

**Comment by MiChAeLoKGB** [comment]
I tried messing with Asteroids in SEToolbox recently, before I knew that feature was broken, but I came to the realization that asteroids have to have a small amount of stone in order for it to be created. Removing all stone from an asteroid probably causes it to not exist, but since there are other ores in the asteroid, the game doesn't know how to handle it, throwing the exception. 

Instead of trying to remove all the stone, see if removing all the stone except for 1 unit per asteroid (if possible) helps out any. I'm not a programmer so all that code is Greek to me, but hopefully this information helps out.

**Comment by MiChAeLoKGB** [comment]
I'm not removing it from an asteroid. I'm modifying the definition files so it never gets created in the first place.

**Comment by MiChAeLoKGB** [comment]
Ah I see. What is it you're trying to accomplish? Just simply removing all stone from any world generated? Or something else?

**Comment by MiChAeLoKGB** [comment]
It's a Materials Mod. Something like this: http://steamcommunity.com/sharedfiles/filedetails/?id=392674650

**Comment by MiChAeLoKGB** [comment]
Hi,

please post the mod that is causing the problem and I will pass it to programmers who will take a look at it. Thank you.

**Comment by MiChAeLoKGB** [comment]
Phand, I'll DB it when I get home from work today. However, all that's needed is a voxelMaterial.sbc with all

```
<MinedOre>Stone</MinedOre>
```

entries changed to

```
<MinedOre>Ice</MinedOre>
```

Phand Mod is here: https://www.dropbox.com/s/ovb5er5esjcx6fr/CometTestMod.zip?dl=0

**Comment by MiChAeLoKGB** [comment]
Hi,

retested and reproduced. This evil dividing by zero. Thank you for providing the mod.
